### ISSUE TITLE
latex equations

### ISSUE THREAD

**Issue by YZhao0123** [swarm-lab/editR#11] opened 2015-09-15 14:49 UTC
The latex equation seems to be knitted incorrectly, for example: $V_1$ is shown as (V_1) in the preview.

**Comment by sjmgarnier** [comment] 2015-09-15 16:12
@RAATSsss This is weird, I do not have this problem here. How old is your editR version? I had fixed this problem a while back now.

**Comment by sjmgarnier** [comment] 2015-10-08 19:27
Closing because the bug is not confirmed.

**Closed as completed by sjmgarnier** 2015-10-08 19:27 UTC

**Comment by YZhao0123** [comment] 2015-11-05 13:41
Sorry sjmarnier, 
I was pulled off on something else since I posted this problem. I am using editR version 0.2.0.

I tried the latex equation of $V_1$ again, it works fine if I knit it into html or word or pdf but in the editR review it looks like \ (V_1\ ) (there is no space between \ and (, but seems github will swallow the \ without the space)

I am not an expert in either latex or rmarkdown so I am not sure what the problem might be in this situation.

Thanks
